# Generated by Django 5.2.6 on 2026-06-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sermon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("preacher", models.CharField(max_length=150)),
                ("bible_text", models.CharField(blank=True, max_length=255)),
                ("sermon_date", models.DateField()),
                ("summary", models.TextField()),
                ("youtube_link", models.URLField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-sermon_date"],
            },
        ),
    ]
