# Generated by Django 5.2.6 on 2026-06-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sermons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sermon",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="sermons/audio/"),
        ),
        migrations.AddField(
            model_name="sermon",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="sermons/images/"),
        ),
        migrations.AddField(
            model_name="sermon",
            name="pdf_notes",
            field=models.FileField(blank=True, null=True, upload_to="sermons/pdfs/"),
        ),
    ]
