# Generated by Django 5.2.6 on 2026-06-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("giving", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contribution",
            options={"ordering": ["-contribution_date"]},
        ),
    ]
