# Generated by Django 5.2.6 on 2026-06-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChurchLeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("LEAD_PASTOR", "Lead Pastor"),
                            ("ASSOCIATE_PASTOR", "Associate Pastor"),
                            ("ELDER", "Elder"),
                            ("DEACON", "Deacon"),
                            ("SECRETARY", "Secretary"),
                            ("TREASURER", "Treasurer"),
                            ("YOUTH_PASTOR", "Youth Pastor"),
                            ("WOMEN_LEADER", "Women Leader"),
                            ("MEN_LEADER", "Men Leader"),
                            ("CHOIR_LEADER", "Choir Leader"),
                        ],
                        max_length=50,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="leaders/"),
                ),
                ("biography", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
