# Generated by Django 5.2.6 on 2026-06-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counselling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="counsellingrequest",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="counsellingrequest",
            name="scheduled_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="counsellingrequest",
            name="scheduled_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
