# Generated by Django 5.2.6 on 2026-06-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("STAFF", "Staff"), ("VISITOR", "Visitor")],
                default="VISITOR",
                max_length=20,
            ),
        ),
    ]
