# Generated by Django 5.2.6 on 2026-06-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_role_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("MEMBER", "Member"),
                    ("PASTOR", "Pastor"),
                    ("SECRETARY", "Secretary"),
                    ("TREASURER", "Treasurer"),
                    ("MINISTRY_LEADER", "Ministry Leader"),
                    ("INTERCESSOR", "Intercessor"),
                    ("SUPER_ADMIN", "Super Admin"),
                ],
                default="MEMBER",
                max_length=30,
            ),
        ),
    ]
