# Generated by Django 5.2.6 on 2026-07-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="biography",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="date_joined_ministry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="user",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="office",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.AddField(
            model_name="user",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="youtube",
            field=models.URLField(blank=True, null=True),
        ),
    ]
