# Generated by Django 5.2.6 on 2026-07-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_biography_user_date_joined_ministry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_head_leader",
            field=models.BooleanField(
                default=False,
                help_text="Check this for the Senior Pastor or overall head of the church.",
            ),
        ),
    ]
