# Generated by Django 5.2.6 on 2026-07-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_is_head_leader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMINISTRATOR", "Administrator"),
                    ("SECRETARY", "Secretary"),
                    ("PASTOR", "Pastor"),
                    ("TREASURER", "Treasurer"),
                    ("MEDIA", "Media"),
                    ("MEMBER", "Member"),
                ],
                default="MEMBER",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("STAFF", "Staff"),
                    ("VISITOR", "Visitor"),
                    ("ADMINISTRATOR", "Administrator"),
                ],
                default="VISITOR",
                max_length=20,
            ),
        ),
    ]
