# Generated by Django 5.2.6 on 2026-07-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_role_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMINISTRATOR", "Administrator"),
                    ("SECRETARY", "Secretary"),
                    ("PASTOR", "Pastor"),
                    ("TREASURER", "Treasurer"),
                    ("MINISTER", "Minister"),
                    ("MEMBER", "Member"),
                ],
                default="MEMBER",
                max_length=30,
            ),
        ),
    ]
