# Generated by Django 5.2.6 on 2026-06-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberfollowup",
            name="visit_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="memberfollowup",
            name="visit_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="memberfollowup",
            name="visit_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="memberfollowup",
            name="visit_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memberfollowup",
            name="visit_type",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
