# Generated by Django 5.2.6 on 2026-06-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={"ordering": ["-created_at"]},
        ),
    ]
