# Generated by Django 5.2.6 on 2026-06-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayerrequest",
            name="pastor_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="prayerrequest",
            name="prayed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prayerrequest",
            name="prayed_by",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="prayerrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("PRAYED", "Prayed For"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
