# Generated by Django 5.2.6 on 2026-06-18 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prayers",
            "0002_prayerrequest_pastor_comment_prayerrequest_prayed_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="prayerrequest",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_prayers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
