# Generated by Django 5.2.6 on 2026-06-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prayers", "0003_prayerrequest_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="prayerrequest",
            name="answered_testimony",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="prayerrequest",
            name="follow_up_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prayerrequest",
            name="is_confidential",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="prayerrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
