# Generated by Django 5.2.6 on 2026-06-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_role_member_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
