# Generated by Django 5.2.6 on 2026-06-16 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_member_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_departments",
                to="members.member",
            ),
        ),
    ]
