# Generated by Django 5.2.6 on 2026-06-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_member_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="member",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SINGLE", "Single"),
                    ("MARRIED", "Married"),
                    ("DIVORCED", "Divorced"),
                    ("WIDOWED", "Widowed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="next_of_kin",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="member",
            name="next_of_kin_contact",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="member",
            name="number_of_children",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="member",
            name="parish",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="member",
            name="sub_county",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="member",
            name="village",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="member",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
