# Generated by Django 5.2.6 on 2026-06-16 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_member_district_member_marital_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="baptism_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="baptism_place",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="member",
            name="church_where_saved",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="member",
            name="date_saved",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="desired_ministry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interested_members",
                to="members.department",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="education_level",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="member",
            name="employer",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="member",
            name="former_church",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="member",
            name="former_pastor",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="member",
            name="is_baptized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="is_renting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="is_student",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="landlord_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="member",
            name="occupation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="member",
            name="place_of_work",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="member",
            name="previous_ministry",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="member",
            name="school_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="member",
            name="years_at_mpc",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
