# Generated by Django 5.2.6 on 2026-08-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_member_baptism_date_member_baptism_place_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_verified", models.BooleanField(default=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
