# Generated by Django 5.2.6 on 2026-06-02 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("SUNDAY", "Sunday Worship"),
                            ("BIBLE_STUDY", "Bible Study"),
                            ("PRAYER", "Prayer Meeting"),
                            ("YOUTH", "Youth Service"),
                            ("SPECIAL", "Special Event"),
                        ],
                        max_length=20,
                    ),
                ),
                ("service_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-recorded_at"]},
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="service_date",
        ),
        migrations.AddField(
            model_name="attendance",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.service",
            ),
        ),
    ]
